/**
 * This class is generated by jOOQ
 */
package org.gradle.execom;


import javax.annotation.Generated;

import org.gradle.execom.tables.Employee;
import org.gradle.execom.tables.Project;
import org.gradle.execom.tables.Projectinfo;
import org.gradle.execom.tables.Tagcloud;
import org.gradle.execom.tables.Tagcloudemp;
import org.gradle.execom.tables.Tagclouds;
import org.gradle.execom.tables.records.EmployeeRecord;
import org.gradle.execom.tables.records.ProjectRecord;
import org.gradle.execom.tables.records.ProjectinfoRecord;
import org.gradle.execom.tables.records.TagcloudRecord;
import org.gradle.execom.tables.records.TagcloudempRecord;
import org.gradle.execom.tables.records.TagcloudsRecord;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>execom</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<EmployeeRecord> KEY_EMPLOYEE_PRIMARY = UniqueKeys0.KEY_EMPLOYEE_PRIMARY;
	public static final UniqueKey<ProjectRecord> KEY_PROJECT_PRIMARY = UniqueKeys0.KEY_PROJECT_PRIMARY;
	public static final UniqueKey<ProjectinfoRecord> KEY_PROJECTINFO_PRIMARY = UniqueKeys0.KEY_PROJECTINFO_PRIMARY;
	public static final UniqueKey<TagcloudRecord> KEY_TAGCLOUD_PRIMARY = UniqueKeys0.KEY_TAGCLOUD_PRIMARY;
	public static final UniqueKey<TagcloudempRecord> KEY_TAGCLOUDEMP_PRIMARY = UniqueKeys0.KEY_TAGCLOUDEMP_PRIMARY;
	public static final UniqueKey<TagcloudsRecord> KEY_TAGCLOUDS_PRIMARY = UniqueKeys0.KEY_TAGCLOUDS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<ProjectinfoRecord, ProjectRecord> FK_PROJECTINFO1 = ForeignKeys0.FK_PROJECTINFO1;
	public static final ForeignKey<ProjectinfoRecord, EmployeeRecord> FK_PROJECTINFO2 = ForeignKeys0.FK_PROJECTINFO2;
	public static final ForeignKey<TagcloudempRecord, TagcloudRecord> FK_TAGCLOUDEMP = ForeignKeys0.FK_TAGCLOUDEMP;
	public static final ForeignKey<TagcloudempRecord, EmployeeRecord> FK_TAGCLOUDEMP2 = ForeignKeys0.FK_TAGCLOUDEMP2;
	public static final ForeignKey<TagcloudsRecord, TagcloudRecord> FK_TAGCLOUDS = ForeignKeys0.FK_TAGCLOUDS;
	public static final ForeignKey<TagcloudsRecord, ProjectRecord> FK_TAGCLOUDS2 = ForeignKeys0.FK_TAGCLOUDS2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<EmployeeRecord> KEY_EMPLOYEE_PRIMARY = createUniqueKey(Employee.EMPLOYEE, Employee.EMPLOYEE.IDEMPLOYEE);
		public static final UniqueKey<ProjectRecord> KEY_PROJECT_PRIMARY = createUniqueKey(Project.PROJECT, Project.PROJECT.IDPROJECT);
		public static final UniqueKey<ProjectinfoRecord> KEY_PROJECTINFO_PRIMARY = createUniqueKey(Projectinfo.PROJECTINFO, Projectinfo.PROJECTINFO.IDPROJECT, Projectinfo.PROJECTINFO.IDEMPLOYEE);
		public static final UniqueKey<TagcloudRecord> KEY_TAGCLOUD_PRIMARY = createUniqueKey(Tagcloud.TAGCLOUD, Tagcloud.TAGCLOUD.IDTAGCLOUD);
		public static final UniqueKey<TagcloudempRecord> KEY_TAGCLOUDEMP_PRIMARY = createUniqueKey(Tagcloudemp.TAGCLOUDEMP, Tagcloudemp.TAGCLOUDEMP.IDTAGCLOUD, Tagcloudemp.TAGCLOUDEMP.IDEMPLOYEE);
		public static final UniqueKey<TagcloudsRecord> KEY_TAGCLOUDS_PRIMARY = createUniqueKey(Tagclouds.TAGCLOUDS, Tagclouds.TAGCLOUDS.IDTAGCLOUD, Tagclouds.TAGCLOUDS.IDPROJECT);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<ProjectinfoRecord, ProjectRecord> FK_PROJECTINFO1 = createForeignKey(org.gradle.execom.Keys.KEY_PROJECT_PRIMARY, Projectinfo.PROJECTINFO, Projectinfo.PROJECTINFO.IDPROJECT);
		public static final ForeignKey<ProjectinfoRecord, EmployeeRecord> FK_PROJECTINFO2 = createForeignKey(org.gradle.execom.Keys.KEY_EMPLOYEE_PRIMARY, Projectinfo.PROJECTINFO, Projectinfo.PROJECTINFO.IDEMPLOYEE);
		public static final ForeignKey<TagcloudempRecord, TagcloudRecord> FK_TAGCLOUDEMP = createForeignKey(org.gradle.execom.Keys.KEY_TAGCLOUD_PRIMARY, Tagcloudemp.TAGCLOUDEMP, Tagcloudemp.TAGCLOUDEMP.IDTAGCLOUD);
		public static final ForeignKey<TagcloudempRecord, EmployeeRecord> FK_TAGCLOUDEMP2 = createForeignKey(org.gradle.execom.Keys.KEY_EMPLOYEE_PRIMARY, Tagcloudemp.TAGCLOUDEMP, Tagcloudemp.TAGCLOUDEMP.IDEMPLOYEE);
		public static final ForeignKey<TagcloudsRecord, TagcloudRecord> FK_TAGCLOUDS = createForeignKey(org.gradle.execom.Keys.KEY_TAGCLOUD_PRIMARY, Tagclouds.TAGCLOUDS, Tagclouds.TAGCLOUDS.IDTAGCLOUD);
		public static final ForeignKey<TagcloudsRecord, ProjectRecord> FK_TAGCLOUDS2 = createForeignKey(org.gradle.execom.Keys.KEY_PROJECT_PRIMARY, Tagclouds.TAGCLOUDS, Tagclouds.TAGCLOUDS.IDPROJECT);
	}
}
