INSERT INTO EMPLOYEE (
   NAME_EMPLOYEE  ,
   GENDER ,
   DATE_OF_BIRTH ,
   ADDRESS,
   PHONE_NUMBER ,
   EMAIL ,
   EMERGENCY_PHONE_NUMBER ,
   START_DATE ,
   END_DATE  ,
   START_DATE_FROM_BOOKLET ,
   USERNAME ,
   ID_CARD_NUMBER ,
   PASSPORT_NUMBER ,
   YEARS_OF_WORKING_EXP_IN_EXECOM ,
   YEARS_OF_WORKING_EXP ,
   PLACE_OF_BIRTH,
   TRAINING_LEARNING_PRIORITY,
   LICENCES_CERTIFICATES,
   AWARDS,
   CONTRACT_TYPE,
   COMMUNICATION,
   FAST_LEARNING,
   OPEN_TO_CHANGE,
   TEAM_PLAYER,
   PROACTIVE_COMMUNICATION,
   INTERPERSONAL_SKILLS,
   KNOWLEDGE_SHARING,
   JUDGEMENT,
   DECISION_MAKING,
   INFLUENCING,
   LEADERSHIP,
   COACHING,             
   ORGANIZATIONAL_SKILLS )
   VALUES('Petar Petrovic', 'm', '1969-05-20', 'Bulevar Oslobodjenja 55, Novi Sad', '0621212123', 'petar@gmail.com',
   '0661001010', '2005-01-12', NULL, '1995-02-25', 'ppetar', 123123123, 123123123, 10, 20, 'Novi Sad', 
   'vrlo visoka', 'Microsoft certificate', 'Prvi truba Guce', 'na neodredjeno vreme', 3, 4 , 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 5);

   INSERT INTO EMPLOYEE (
   NAME_EMPLOYEE  ,
   GENDER ,
   DATE_OF_BIRTH ,
   ADDRESS,
   PHONE_NUMBER ,
   EMAIL ,
   EMERGENCY_PHONE_NUMBER ,
   START_DATE ,
   END_DATE  ,
   START_DATE_FROM_BOOKLET ,
   USERNAME ,
   ID_CARD_NUMBER ,
   PASSPORT_NUMBER ,
   YEARS_OF_WORKING_EXP_IN_EXECOM ,
   YEARS_OF_WORKING_EXP ,
   PLACE_OF_BIRTH,
   TRAINING_LEARNING_PRIORITY,
   LICENCES_CERTIFICATES,
   AWARDS,
   CONTRACT_TYPE,
   COMMUNICATION,
   FAST_LEARNING,
   OPEN_TO_CHANGE,
   TEAM_PLAYER,
   PROACTIVE_COMMUNICATION,
   INTERPERSONAL_SKILLS,
   KNOWLEDGE_SHARING,
   JUDGEMENT,
   DECISION_MAKING,
   INFLUENCING,
   LEADERSHIP,
   COACHING,             
   ORGANIZATIONAL_SKILLS )
   VALUES('Milos Milosevic', 'm', '1988-05-20', 'Bulevar Oslobodjenja 26, Novi Sad', '0625512123', 'milos@gmail.com',
   '0661001010', '2010-01-12', NULL, '2008-02-25', 'mmilos', 123123123, 123123123, 5, 7, 'Zrenjanin', 
   'vrlo visoka', 'Microsoft certificate, Cisco certificate', 'Recitator godine', 'na neodredjeno vreme', 3, 4 , 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 5);
   
   INSERT INTO EMPLOYEE (
   NAME_EMPLOYEE  ,
   GENDER ,
   DATE_OF_BIRTH ,
   ADDRESS,
   PHONE_NUMBER ,
   EMAIL ,
   EMERGENCY_PHONE_NUMBER ,
   START_DATE ,
   END_DATE  ,
   START_DATE_FROM_BOOKLET ,
   USERNAME ,
   ID_CARD_NUMBER ,
   PASSPORT_NUMBER ,
   YEARS_OF_WORKING_EXP_IN_EXECOM ,
   YEARS_OF_WORKING_EXP ,
   PLACE_OF_BIRTH,
   TRAINING_LEARNING_PRIORITY,
   LICENCES_CERTIFICATES,
   AWARDS,
   CONTRACT_TYPE,
   COMMUNICATION,
   FAST_LEARNING,
   OPEN_TO_CHANGE,
   TEAM_PLAYER,
   PROACTIVE_COMMUNICATION,
   INTERPERSONAL_SKILLS,
   KNOWLEDGE_SHARING,
   JUDGEMENT,
   DECISION_MAKING,
   INFLUENCING,
   LEADERSHIP,
   COACHING,             
   ORGANIZATIONAL_SKILLS )
   VALUES('Sneza Snegic', 'z', '1990-05-25', 'Danila Kisa 24, Novi Sad', '0691212123', 'sneza@gmail.com',
   '0661001010', '2005-01-12', NULL, '1995-02-25', 'ssnegic', 123123123, 123123123, 10, 20, 'Novi Sad', 
   'vrlo visoka', 'Microsoft certificate', 'The best clean coder of SummerCodeFun', 'honorarno', 3, 4 , 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 5);
   
   INSERT INTO PROJECT(NAME_PROJECT, DURATION_OF_PROJECT)
   VALUES( 'HRTool', 4);
   INSERT INTO PROJECT(NAME_PROJECT, DURATION_OF_PROJECT)
   VALUES( 'ShippingWIFI', 25);
   INSERT INTO PROJECT(NAME_PROJECT, DURATION_OF_PROJECT)
   VALUES( 'Smart house vol.1', 15);
   
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('software engineer', 'position');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('team leader', 'position');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('WPF', 'technologie');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('SPRING', 'technologie');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('.NET', 'technologie');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('mySQL', 'database');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('Oracle', 'database');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('Microsoft Visual Studio', 'ide');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('Eclipse', 'ide');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('server', 'platform');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('desktop', 'platform');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('web', 'platform');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('automoto', 'industry');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('Windows 7', 'OS');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('Ubuntu', 'OS');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('visoka', 'education');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('srednja', 'education');
   INSERT INTO TAGCLOUD (NAME_TAGCLOUD, TIP_TAGCLOUD)
   VALUES('english', 'foreign languages');
   