/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables.records;


import javax.annotation.Generated;

import org.gradle.execom.tables.Tagcloudemp;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagcloudempRecord extends UpdatableRecordImpl<TagcloudempRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -1009506474;

	/**
	 * Setter for <code>execom.tagcloudemp.IDTAGCLOUD</code>.
	 */
	public void setIdtagcloud(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>execom.tagcloudemp.IDTAGCLOUD</code>.
	 */
	public Integer getIdtagcloud() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>execom.tagcloudemp.IDEMPLOYEE</code>.
	 */
	public void setIdemployee(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>execom.tagcloudemp.IDEMPLOYEE</code>.
	 */
	public Integer getIdemployee() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Tagcloudemp.TAGCLOUDEMP.IDTAGCLOUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Tagcloudemp.TAGCLOUDEMP.IDEMPLOYEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdtagcloud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdemployee();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudempRecord value1(Integer value) {
		setIdtagcloud(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudempRecord value2(Integer value) {
		setIdemployee(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudempRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TagcloudempRecord
	 */
	public TagcloudempRecord() {
		super(Tagcloudemp.TAGCLOUDEMP);
	}

	/**
	 * Create a detached, initialised TagcloudempRecord
	 */
	public TagcloudempRecord(Integer idtagcloud, Integer idemployee) {
		super(Tagcloudemp.TAGCLOUDEMP);

		setValue(0, idtagcloud);
		setValue(1, idemployee);
	}
}
