/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.gradle.execom.Execom;
import org.gradle.execom.Keys;
import org.gradle.execom.tables.records.TagcloudRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagcloud extends TableImpl<TagcloudRecord> {

	private static final long serialVersionUID = 1919913631;

	/**
	 * The reference instance of <code>execom.tagcloud</code>
	 */
	public static final Tagcloud TAGCLOUD = new Tagcloud();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TagcloudRecord> getRecordType() {
		return TagcloudRecord.class;
	}

	/**
	 * The column <code>execom.tagcloud.IDTAGCLOUD</code>.
	 */
	public final TableField<TagcloudRecord, Integer> IDTAGCLOUD = createField("IDTAGCLOUD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>execom.tagcloud.NAME_TAGCLOUD</code>.
	 */
	public final TableField<TagcloudRecord, String> NAME_TAGCLOUD = createField("NAME_TAGCLOUD", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>execom.tagcloud.TIP_TAGCLOUD</code>.
	 */
	public final TableField<TagcloudRecord, String> TIP_TAGCLOUD = createField("TIP_TAGCLOUD", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * Create a <code>execom.tagcloud</code> table reference
	 */
	public Tagcloud() {
		this("tagcloud", null);
	}

	/**
	 * Create an aliased <code>execom.tagcloud</code> table reference
	 */
	public Tagcloud(String alias) {
		this(alias, TAGCLOUD);
	}

	private Tagcloud(String alias, Table<TagcloudRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tagcloud(String alias, Table<TagcloudRecord> aliased, Field<?>[] parameters) {
		super(alias, Execom.EXECOM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TagcloudRecord> getPrimaryKey() {
		return Keys.KEY_TAGCLOUD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TagcloudRecord>> getKeys() {
		return Arrays.<UniqueKey<TagcloudRecord>>asList(Keys.KEY_TAGCLOUD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Tagcloud as(String alias) {
		return new Tagcloud(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Tagcloud rename(String name) {
		return new Tagcloud(name, null);
	}
}
