/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables.records;


import javax.annotation.Generated;

import org.gradle.execom.tables.Tagclouds;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagcloudsRecord extends UpdatableRecordImpl<TagcloudsRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 72940055;

	/**
	 * Setter for <code>execom.tagclouds.IDTAGCLOUD</code>.
	 */
	public void setIdtagcloud(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>execom.tagclouds.IDTAGCLOUD</code>.
	 */
	public Integer getIdtagcloud() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>execom.tagclouds.IDPROJECT</code>.
	 */
	public void setIdproject(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>execom.tagclouds.IDPROJECT</code>.
	 */
	public Integer getIdproject() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Tagclouds.TAGCLOUDS.IDTAGCLOUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Tagclouds.TAGCLOUDS.IDPROJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdtagcloud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdproject();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudsRecord value1(Integer value) {
		setIdtagcloud(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudsRecord value2(Integer value) {
		setIdproject(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudsRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TagcloudsRecord
	 */
	public TagcloudsRecord() {
		super(Tagclouds.TAGCLOUDS);
	}

	/**
	 * Create a detached, initialised TagcloudsRecord
	 */
	public TagcloudsRecord(Integer idtagcloud, Integer idproject) {
		super(Tagclouds.TAGCLOUDS);

		setValue(0, idtagcloud);
		setValue(1, idproject);
	}
}
