/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables.records;


import javax.annotation.Generated;

import org.gradle.execom.tables.Tagcloud;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagcloudRecord extends UpdatableRecordImpl<TagcloudRecord> implements Record3<Integer, String, String> {

	private static final long serialVersionUID = 1320808240;

	/**
	 * Setter for <code>execom.tagcloud.IDTAGCLOUD</code>.
	 */
	public void setIdtagcloud(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>execom.tagcloud.IDTAGCLOUD</code>.
	 */
	public Integer getIdtagcloud() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>execom.tagcloud.NAME_TAGCLOUD</code>.
	 */
	public void setNameTagcloud(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>execom.tagcloud.NAME_TAGCLOUD</code>.
	 */
	public String getNameTagcloud() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>execom.tagcloud.TIP_TAGCLOUD</code>.
	 */
	public void setTipTagcloud(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>execom.tagcloud.TIP_TAGCLOUD</code>.
	 */
	public String getTipTagcloud() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, String, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Tagcloud.TAGCLOUD.IDTAGCLOUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Tagcloud.TAGCLOUD.NAME_TAGCLOUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Tagcloud.TAGCLOUD.TIP_TAGCLOUD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdtagcloud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNameTagcloud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTipTagcloud();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudRecord value1(Integer value) {
		setIdtagcloud(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudRecord value2(String value) {
		setNameTagcloud(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudRecord value3(String value) {
		setTipTagcloud(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagcloudRecord values(Integer value1, String value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TagcloudRecord
	 */
	public TagcloudRecord() {
		super(Tagcloud.TAGCLOUD);
	}

	/**
	 * Create a detached, initialised TagcloudRecord
	 */
	public TagcloudRecord(Integer idtagcloud, String nameTagcloud, String tipTagcloud) {
		super(Tagcloud.TAGCLOUD);

		setValue(0, idtagcloud);
		setValue(1, nameTagcloud);
		setValue(2, tipTagcloud);
	}
}
