/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables;


import java.math.BigInteger;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.gradle.execom.Execom;
import org.gradle.execom.Keys;
import org.gradle.execom.tables.records.EmployeeRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends TableImpl<EmployeeRecord> {

	private static final long serialVersionUID = 1017363805;

	/**
	 * The reference instance of <code>execom.employee</code>
	 */
	public static final Employee EMPLOYEE = new Employee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmployeeRecord> getRecordType() {
		return EmployeeRecord.class;
	}

	/**
	 * The column <code>execom.employee.IDEMPLOYEE</code>.
	 */
	public final TableField<EmployeeRecord, Integer> IDEMPLOYEE = createField("IDEMPLOYEE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>execom.employee.NAME_EMPLOYEE</code>.
	 */
	public final TableField<EmployeeRecord, String> NAME_EMPLOYEE = createField("NAME_EMPLOYEE", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>execom.employee.GENDER</code>.
	 */
	public final TableField<EmployeeRecord, String> GENDER = createField("GENDER", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>execom.employee.DATE_OF_BIRTH</code>.
	 */
	public final TableField<EmployeeRecord, Date> DATE_OF_BIRTH = createField("DATE_OF_BIRTH", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>execom.employee.ADDRESS</code>.
	 */
	public final TableField<EmployeeRecord, String> ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>execom.employee.PHONE_NUMBER</code>.
	 */
	public final TableField<EmployeeRecord, Long> PHONE_NUMBER = createField("PHONE_NUMBER", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>execom.employee.EMAIL</code>.
	 */
	public final TableField<EmployeeRecord, String> EMAIL = createField("EMAIL", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>execom.employee.EMERGENCY_PHONE_NUMBER</code>.
	 */
	public final TableField<EmployeeRecord, Long> EMERGENCY_PHONE_NUMBER = createField("EMERGENCY_PHONE_NUMBER", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>execom.employee.START_DATE</code>.
	 */
	public final TableField<EmployeeRecord, Date> START_DATE = createField("START_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>execom.employee.END_DATE</code>.
	 */
	public final TableField<EmployeeRecord, Date> END_DATE = createField("END_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>execom.employee.START_DATE_FROM_BOOKLET</code>.
	 */
	public final TableField<EmployeeRecord, Date> START_DATE_FROM_BOOKLET = createField("START_DATE_FROM_BOOKLET", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>execom.employee.USERNAME</code>.
	 */
	public final TableField<EmployeeRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>execom.employee.ID_CARD_NUMBER</code>.
	 */
	public final TableField<EmployeeRecord, BigInteger> ID_CARD_NUMBER = createField("ID_CARD_NUMBER", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(30), this, "");

	/**
	 * The column <code>execom.employee.PASSPORT_NUMBER</code>.
	 */
	public final TableField<EmployeeRecord, BigInteger> PASSPORT_NUMBER = createField("PASSPORT_NUMBER", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(30), this, "");

	/**
	 * The column <code>execom.employee.YEARS_OF_WORKING_EXP_IN_EXECOM</code>.
	 */
	public final TableField<EmployeeRecord, Integer> YEARS_OF_WORKING_EXP_IN_EXECOM = createField("YEARS_OF_WORKING_EXP_IN_EXECOM", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>execom.employee.YEARS_OF_WORKING_EXP</code>.
	 */
	public final TableField<EmployeeRecord, Integer> YEARS_OF_WORKING_EXP = createField("YEARS_OF_WORKING_EXP", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>execom.employee.PLACE_OF_BIRTH</code>.
	 */
	public final TableField<EmployeeRecord, String> PLACE_OF_BIRTH = createField("PLACE_OF_BIRTH", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>execom.employee.TRAINING_LEARNING_PRIORITY</code>.
	 */
	public final TableField<EmployeeRecord, String> TRAINING_LEARNING_PRIORITY = createField("TRAINING_LEARNING_PRIORITY", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>execom.employee.LICENCES_CERTIFICATES</code>.
	 */
	public final TableField<EmployeeRecord, String> LICENCES_CERTIFICATES = createField("LICENCES_CERTIFICATES", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>execom.employee.AWARDS</code>.
	 */
	public final TableField<EmployeeRecord, String> AWARDS = createField("AWARDS", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>execom.employee.CONTRACT_TYPE</code>.
	 */
	public final TableField<EmployeeRecord, String> CONTRACT_TYPE = createField("CONTRACT_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>execom.employee.COMMUNICATION</code>.
	 */
	public final TableField<EmployeeRecord, Short> COMMUNICATION = createField("COMMUNICATION", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.FAST_LEARNING</code>.
	 */
	public final TableField<EmployeeRecord, Short> FAST_LEARNING = createField("FAST_LEARNING", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.OPEN_TO_CHANGE</code>.
	 */
	public final TableField<EmployeeRecord, Short> OPEN_TO_CHANGE = createField("OPEN_TO_CHANGE", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.TEAM_PLAYER</code>.
	 */
	public final TableField<EmployeeRecord, Short> TEAM_PLAYER = createField("TEAM_PLAYER", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.PROACTIVE_COMMUNICATION</code>.
	 */
	public final TableField<EmployeeRecord, Short> PROACTIVE_COMMUNICATION = createField("PROACTIVE_COMMUNICATION", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.INTERPERSONAL_SKILLS</code>.
	 */
	public final TableField<EmployeeRecord, Short> INTERPERSONAL_SKILLS = createField("INTERPERSONAL_SKILLS", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.KNOWLEDGE_SHARING</code>.
	 */
	public final TableField<EmployeeRecord, Short> KNOWLEDGE_SHARING = createField("KNOWLEDGE_SHARING", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.JUDGEMENT</code>.
	 */
	public final TableField<EmployeeRecord, Short> JUDGEMENT = createField("JUDGEMENT", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.DECISION_MAKING</code>.
	 */
	public final TableField<EmployeeRecord, Short> DECISION_MAKING = createField("DECISION_MAKING", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.INFLUENCING</code>.
	 */
	public final TableField<EmployeeRecord, Short> INFLUENCING = createField("INFLUENCING", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.LEADERSHIP</code>.
	 */
	public final TableField<EmployeeRecord, Short> LEADERSHIP = createField("LEADERSHIP", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.COACHING</code>.
	 */
	public final TableField<EmployeeRecord, Short> COACHING = createField("COACHING", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>execom.employee.ORGANIZATIONAL_SKILLS</code>.
	 */
	public final TableField<EmployeeRecord, Short> ORGANIZATIONAL_SKILLS = createField("ORGANIZATIONAL_SKILLS", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * Create a <code>execom.employee</code> table reference
	 */
	public Employee() {
		this("employee", null);
	}

	/**
	 * Create an aliased <code>execom.employee</code> table reference
	 */
	public Employee(String alias) {
		this(alias, EMPLOYEE);
	}

	private Employee(String alias, Table<EmployeeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Employee(String alias, Table<EmployeeRecord> aliased, Field<?>[] parameters) {
		super(alias, Execom.EXECOM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmployeeRecord> getPrimaryKey() {
		return Keys.KEY_EMPLOYEE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmployeeRecord>> getKeys() {
		return Arrays.<UniqueKey<EmployeeRecord>>asList(Keys.KEY_EMPLOYEE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Employee as(String alias) {
		return new Employee(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Employee rename(String name) {
		return new Employee(name, null);
	}
}
