/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.gradle.execom.Execom;
import org.gradle.execom.Keys;
import org.gradle.execom.tables.records.TagcloudempRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagcloudemp extends TableImpl<TagcloudempRecord> {

	private static final long serialVersionUID = 814701381;

	/**
	 * The reference instance of <code>execom.tagcloudemp</code>
	 */
	public static final Tagcloudemp TAGCLOUDEMP = new Tagcloudemp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TagcloudempRecord> getRecordType() {
		return TagcloudempRecord.class;
	}

	/**
	 * The column <code>execom.tagcloudemp.IDTAGCLOUD</code>.
	 */
	public final TableField<TagcloudempRecord, Integer> IDTAGCLOUD = createField("IDTAGCLOUD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>execom.tagcloudemp.IDEMPLOYEE</code>.
	 */
	public final TableField<TagcloudempRecord, Integer> IDEMPLOYEE = createField("IDEMPLOYEE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>execom.tagcloudemp</code> table reference
	 */
	public Tagcloudemp() {
		this("tagcloudemp", null);
	}

	/**
	 * Create an aliased <code>execom.tagcloudemp</code> table reference
	 */
	public Tagcloudemp(String alias) {
		this(alias, TAGCLOUDEMP);
	}

	private Tagcloudemp(String alias, Table<TagcloudempRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tagcloudemp(String alias, Table<TagcloudempRecord> aliased, Field<?>[] parameters) {
		super(alias, Execom.EXECOM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TagcloudempRecord> getPrimaryKey() {
		return Keys.KEY_TAGCLOUDEMP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TagcloudempRecord>> getKeys() {
		return Arrays.<UniqueKey<TagcloudempRecord>>asList(Keys.KEY_TAGCLOUDEMP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TagcloudempRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TagcloudempRecord, ?>>asList(Keys.FK_TAGCLOUDEMP, Keys.FK_TAGCLOUDEMP2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Tagcloudemp as(String alias) {
		return new Tagcloudemp(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Tagcloudemp rename(String name) {
		return new Tagcloudemp(name, null);
	}
}
