/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.gradle.execom.Execom;
import org.gradle.execom.Keys;
import org.gradle.execom.tables.records.TagcloudsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tagclouds extends TableImpl<TagcloudsRecord> {

	private static final long serialVersionUID = -700117604;

	/**
	 * The reference instance of <code>execom.tagclouds</code>
	 */
	public static final Tagclouds TAGCLOUDS = new Tagclouds();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TagcloudsRecord> getRecordType() {
		return TagcloudsRecord.class;
	}

	/**
	 * The column <code>execom.tagclouds.IDTAGCLOUD</code>.
	 */
	public final TableField<TagcloudsRecord, Integer> IDTAGCLOUD = createField("IDTAGCLOUD", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>execom.tagclouds.IDPROJECT</code>.
	 */
	public final TableField<TagcloudsRecord, Integer> IDPROJECT = createField("IDPROJECT", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>execom.tagclouds</code> table reference
	 */
	public Tagclouds() {
		this("tagclouds", null);
	}

	/**
	 * Create an aliased <code>execom.tagclouds</code> table reference
	 */
	public Tagclouds(String alias) {
		this(alias, TAGCLOUDS);
	}

	private Tagclouds(String alias, Table<TagcloudsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tagclouds(String alias, Table<TagcloudsRecord> aliased, Field<?>[] parameters) {
		super(alias, Execom.EXECOM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TagcloudsRecord> getPrimaryKey() {
		return Keys.KEY_TAGCLOUDS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TagcloudsRecord>> getKeys() {
		return Arrays.<UniqueKey<TagcloudsRecord>>asList(Keys.KEY_TAGCLOUDS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<TagcloudsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<TagcloudsRecord, ?>>asList(Keys.FK_TAGCLOUDS, Keys.FK_TAGCLOUDS2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Tagclouds as(String alias) {
		return new Tagclouds(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Tagclouds rename(String name) {
		return new Tagclouds(name, null);
	}
}
