/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables.records;


import java.math.BigInteger;
import java.sql.Date;

import javax.annotation.Generated;

import org.gradle.execom.tables.Employee;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> {

	private static final long serialVersionUID = 1009199037;

	/**
	 * Setter for <code>execom.employee.IDEMPLOYEE</code>.
	 */
	public void setIdemployee(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>execom.employee.IDEMPLOYEE</code>.
	 */
	public Integer getIdemployee() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>execom.employee.NAME_EMPLOYEE</code>.
	 */
	public void setNameEmployee(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>execom.employee.NAME_EMPLOYEE</code>.
	 */
	public String getNameEmployee() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>execom.employee.GENDER</code>.
	 */
	public void setGender(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>execom.employee.GENDER</code>.
	 */
	public String getGender() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>execom.employee.DATE_OF_BIRTH</code>.
	 */
	public void setDateOfBirth(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>execom.employee.DATE_OF_BIRTH</code>.
	 */
	public Date getDateOfBirth() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>execom.employee.ADDRESS</code>.
	 */
	public void setAddress(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>execom.employee.ADDRESS</code>.
	 */
	public String getAddress() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>execom.employee.PHONE_NUMBER</code>.
	 */
	public void setPhoneNumber(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>execom.employee.PHONE_NUMBER</code>.
	 */
	public Long getPhoneNumber() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>execom.employee.EMAIL</code>.
	 */
	public void setEmail(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>execom.employee.EMAIL</code>.
	 */
	public String getEmail() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>execom.employee.EMERGENCY_PHONE_NUMBER</code>.
	 */
	public void setEmergencyPhoneNumber(Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>execom.employee.EMERGENCY_PHONE_NUMBER</code>.
	 */
	public Long getEmergencyPhoneNumber() {
		return (Long) getValue(7);
	}

	/**
	 * Setter for <code>execom.employee.START_DATE</code>.
	 */
	public void setStartDate(Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>execom.employee.START_DATE</code>.
	 */
	public Date getStartDate() {
		return (Date) getValue(8);
	}

	/**
	 * Setter for <code>execom.employee.END_DATE</code>.
	 */
	public void setEndDate(Date value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>execom.employee.END_DATE</code>.
	 */
	public Date getEndDate() {
		return (Date) getValue(9);
	}

	/**
	 * Setter for <code>execom.employee.START_DATE_FROM_BOOKLET</code>.
	 */
	public void setStartDateFromBooklet(Date value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>execom.employee.START_DATE_FROM_BOOKLET</code>.
	 */
	public Date getStartDateFromBooklet() {
		return (Date) getValue(10);
	}

	/**
	 * Setter for <code>execom.employee.USERNAME</code>.
	 */
	public void setUsername(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>execom.employee.USERNAME</code>.
	 */
	public String getUsername() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>execom.employee.ID_CARD_NUMBER</code>.
	 */
	public void setIdCardNumber(BigInteger value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>execom.employee.ID_CARD_NUMBER</code>.
	 */
	public BigInteger getIdCardNumber() {
		return (BigInteger) getValue(12);
	}

	/**
	 * Setter for <code>execom.employee.PASSPORT_NUMBER</code>.
	 */
	public void setPassportNumber(BigInteger value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>execom.employee.PASSPORT_NUMBER</code>.
	 */
	public BigInteger getPassportNumber() {
		return (BigInteger) getValue(13);
	}

	/**
	 * Setter for <code>execom.employee.YEARS_OF_WORKING_EXP_IN_EXECOM</code>.
	 */
	public void setYearsOfWorkingExpInExecom(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>execom.employee.YEARS_OF_WORKING_EXP_IN_EXECOM</code>.
	 */
	public Integer getYearsOfWorkingExpInExecom() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>execom.employee.YEARS_OF_WORKING_EXP</code>.
	 */
	public void setYearsOfWorkingExp(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>execom.employee.YEARS_OF_WORKING_EXP</code>.
	 */
	public Integer getYearsOfWorkingExp() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>execom.employee.PLACE_OF_BIRTH</code>.
	 */
	public void setPlaceOfBirth(String value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>execom.employee.PLACE_OF_BIRTH</code>.
	 */
	public String getPlaceOfBirth() {
		return (String) getValue(16);
	}

	/**
	 * Setter for <code>execom.employee.TRAINING_LEARNING_PRIORITY</code>.
	 */
	public void setTrainingLearningPriority(String value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>execom.employee.TRAINING_LEARNING_PRIORITY</code>.
	 */
	public String getTrainingLearningPriority() {
		return (String) getValue(17);
	}

	/**
	 * Setter for <code>execom.employee.LICENCES_CERTIFICATES</code>.
	 */
	public void setLicencesCertificates(String value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>execom.employee.LICENCES_CERTIFICATES</code>.
	 */
	public String getLicencesCertificates() {
		return (String) getValue(18);
	}

	/**
	 * Setter for <code>execom.employee.AWARDS</code>.
	 */
	public void setAwards(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>execom.employee.AWARDS</code>.
	 */
	public String getAwards() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>execom.employee.CONTRACT_TYPE</code>.
	 */
	public void setContractType(String value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>execom.employee.CONTRACT_TYPE</code>.
	 */
	public String getContractType() {
		return (String) getValue(20);
	}

	/**
	 * Setter for <code>execom.employee.COMMUNICATION</code>.
	 */
	public void setCommunication(Short value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>execom.employee.COMMUNICATION</code>.
	 */
	public Short getCommunication() {
		return (Short) getValue(21);
	}

	/**
	 * Setter for <code>execom.employee.FAST_LEARNING</code>.
	 */
	public void setFastLearning(Short value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>execom.employee.FAST_LEARNING</code>.
	 */
	public Short getFastLearning() {
		return (Short) getValue(22);
	}

	/**
	 * Setter for <code>execom.employee.OPEN_TO_CHANGE</code>.
	 */
	public void setOpenToChange(Short value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>execom.employee.OPEN_TO_CHANGE</code>.
	 */
	public Short getOpenToChange() {
		return (Short) getValue(23);
	}

	/**
	 * Setter for <code>execom.employee.TEAM_PLAYER</code>.
	 */
	public void setTeamPlayer(Short value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>execom.employee.TEAM_PLAYER</code>.
	 */
	public Short getTeamPlayer() {
		return (Short) getValue(24);
	}

	/**
	 * Setter for <code>execom.employee.PROACTIVE_COMMUNICATION</code>.
	 */
	public void setProactiveCommunication(Short value) {
		setValue(25, value);
	}

	/**
	 * Getter for <code>execom.employee.PROACTIVE_COMMUNICATION</code>.
	 */
	public Short getProactiveCommunication() {
		return (Short) getValue(25);
	}

	/**
	 * Setter for <code>execom.employee.INTERPERSONAL_SKILLS</code>.
	 */
	public void setInterpersonalSkills(Short value) {
		setValue(26, value);
	}

	/**
	 * Getter for <code>execom.employee.INTERPERSONAL_SKILLS</code>.
	 */
	public Short getInterpersonalSkills() {
		return (Short) getValue(26);
	}

	/**
	 * Setter for <code>execom.employee.KNOWLEDGE_SHARING</code>.
	 */
	public void setKnowledgeSharing(Short value) {
		setValue(27, value);
	}

	/**
	 * Getter for <code>execom.employee.KNOWLEDGE_SHARING</code>.
	 */
	public Short getKnowledgeSharing() {
		return (Short) getValue(27);
	}

	/**
	 * Setter for <code>execom.employee.JUDGEMENT</code>.
	 */
	public void setJudgement(Short value) {
		setValue(28, value);
	}

	/**
	 * Getter for <code>execom.employee.JUDGEMENT</code>.
	 */
	public Short getJudgement() {
		return (Short) getValue(28);
	}

	/**
	 * Setter for <code>execom.employee.DECISION_MAKING</code>.
	 */
	public void setDecisionMaking(Short value) {
		setValue(29, value);
	}

	/**
	 * Getter for <code>execom.employee.DECISION_MAKING</code>.
	 */
	public Short getDecisionMaking() {
		return (Short) getValue(29);
	}

	/**
	 * Setter for <code>execom.employee.INFLUENCING</code>.
	 */
	public void setInfluencing(Short value) {
		setValue(30, value);
	}

	/**
	 * Getter for <code>execom.employee.INFLUENCING</code>.
	 */
	public Short getInfluencing() {
		return (Short) getValue(30);
	}

	/**
	 * Setter for <code>execom.employee.LEADERSHIP</code>.
	 */
	public void setLeadership(Short value) {
		setValue(31, value);
	}

	/**
	 * Getter for <code>execom.employee.LEADERSHIP</code>.
	 */
	public Short getLeadership() {
		return (Short) getValue(31);
	}

	/**
	 * Setter for <code>execom.employee.COACHING</code>.
	 */
	public void setCoaching(Short value) {
		setValue(32, value);
	}

	/**
	 * Getter for <code>execom.employee.COACHING</code>.
	 */
	public Short getCoaching() {
		return (Short) getValue(32);
	}

	/**
	 * Setter for <code>execom.employee.ORGANIZATIONAL_SKILLS</code>.
	 */
	public void setOrganizationalSkills(Short value) {
		setValue(33, value);
	}

	/**
	 * Getter for <code>execom.employee.ORGANIZATIONAL_SKILLS</code>.
	 */
	public Short getOrganizationalSkills() {
		return (Short) getValue(33);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmployeeRecord
	 */
	public EmployeeRecord() {
		super(Employee.EMPLOYEE);
	}

	/**
	 * Create a detached, initialised EmployeeRecord
	 */
	public EmployeeRecord(Integer idemployee, String nameEmployee, String gender, Date dateOfBirth, String address, Long phoneNumber, String email, Long emergencyPhoneNumber, Date startDate, Date endDate, Date startDateFromBooklet, String username, BigInteger idCardNumber, BigInteger passportNumber, Integer yearsOfWorkingExpInExecom, Integer yearsOfWorkingExp, String placeOfBirth, String trainingLearningPriority, String licencesCertificates, String awards, String contractType, Short communication, Short fastLearning, Short openToChange, Short teamPlayer, Short proactiveCommunication, Short interpersonalSkills, Short knowledgeSharing, Short judgement, Short decisionMaking, Short influencing, Short leadership, Short coaching, Short organizationalSkills) {
		super(Employee.EMPLOYEE);

		setValue(0, idemployee);
		setValue(1, nameEmployee);
		setValue(2, gender);
		setValue(3, dateOfBirth);
		setValue(4, address);
		setValue(5, phoneNumber);
		setValue(6, email);
		setValue(7, emergencyPhoneNumber);
		setValue(8, startDate);
		setValue(9, endDate);
		setValue(10, startDateFromBooklet);
		setValue(11, username);
		setValue(12, idCardNumber);
		setValue(13, passportNumber);
		setValue(14, yearsOfWorkingExpInExecom);
		setValue(15, yearsOfWorkingExp);
		setValue(16, placeOfBirth);
		setValue(17, trainingLearningPriority);
		setValue(18, licencesCertificates);
		setValue(19, awards);
		setValue(20, contractType);
		setValue(21, communication);
		setValue(22, fastLearning);
		setValue(23, openToChange);
		setValue(24, teamPlayer);
		setValue(25, proactiveCommunication);
		setValue(26, interpersonalSkills);
		setValue(27, knowledgeSharing);
		setValue(28, judgement);
		setValue(29, decisionMaking);
		setValue(30, influencing);
		setValue(31, leadership);
		setValue(32, coaching);
		setValue(33, organizationalSkills);
	}
}
