/**
 * This class is generated by jOOQ
 */
package org.gradle.execom;


import javax.annotation.Generated;

import org.gradle.execom.tables.Employee;
import org.gradle.execom.tables.Project;
import org.gradle.execom.tables.Projectinfo;
import org.gradle.execom.tables.Tagcloud;
import org.gradle.execom.tables.Tagcloudemp;
import org.gradle.execom.tables.Tagclouds;


/**
 * Convenience access to all tables in execom
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table execom.employee
	 */
	public static final Employee EMPLOYEE = org.gradle.execom.tables.Employee.EMPLOYEE;

	/**
	 * The table execom.project
	 */
	public static final Project PROJECT = org.gradle.execom.tables.Project.PROJECT;

	/**
	 * The table execom.projectinfo
	 */
	public static final Projectinfo PROJECTINFO = org.gradle.execom.tables.Projectinfo.PROJECTINFO;

	/**
	 * The table execom.tagcloud
	 */
	public static final Tagcloud TAGCLOUD = org.gradle.execom.tables.Tagcloud.TAGCLOUD;

	/**
	 * The table execom.tagcloudemp
	 */
	public static final Tagcloudemp TAGCLOUDEMP = org.gradle.execom.tables.Tagcloudemp.TAGCLOUDEMP;

	/**
	 * The table execom.tagclouds
	 */
	public static final Tagclouds TAGCLOUDS = org.gradle.execom.tables.Tagclouds.TAGCLOUDS;
}
