/**
 * This class is generated by jOOQ
 */
package org.gradle.execom.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.gradle.execom.Execom;
import org.gradle.execom.Keys;
import org.gradle.execom.tables.records.ProjectinfoRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Projectinfo extends TableImpl<ProjectinfoRecord> {

	private static final long serialVersionUID = 270971217;

	/**
	 * The reference instance of <code>execom.projectinfo</code>
	 */
	public static final Projectinfo PROJECTINFO = new Projectinfo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ProjectinfoRecord> getRecordType() {
		return ProjectinfoRecord.class;
	}

	/**
	 * The column <code>execom.projectinfo.IDPROJECT</code>.
	 */
	public final TableField<ProjectinfoRecord, Integer> IDPROJECT = createField("IDPROJECT", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>execom.projectinfo.IDEMPLOYEE</code>.
	 */
	public final TableField<ProjectinfoRecord, Integer> IDEMPLOYEE = createField("IDEMPLOYEE", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>execom.projectinfo.JOB_RESPONSIBILITIES</code>.
	 */
	public final TableField<ProjectinfoRecord, String> JOB_RESPONSIBILITIES = createField("JOB_RESPONSIBILITIES", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>execom.projectinfo.PROJECT_EXP</code>.
	 */
	public final TableField<ProjectinfoRecord, String> PROJECT_EXP = createField("PROJECT_EXP", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>execom.projectinfo</code> table reference
	 */
	public Projectinfo() {
		this("projectinfo", null);
	}

	/**
	 * Create an aliased <code>execom.projectinfo</code> table reference
	 */
	public Projectinfo(String alias) {
		this(alias, PROJECTINFO);
	}

	private Projectinfo(String alias, Table<ProjectinfoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Projectinfo(String alias, Table<ProjectinfoRecord> aliased, Field<?>[] parameters) {
		super(alias, Execom.EXECOM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ProjectinfoRecord> getPrimaryKey() {
		return Keys.KEY_PROJECTINFO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ProjectinfoRecord>> getKeys() {
		return Arrays.<UniqueKey<ProjectinfoRecord>>asList(Keys.KEY_PROJECTINFO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ProjectinfoRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ProjectinfoRecord, ?>>asList(Keys.FK_PROJECTINFO1, Keys.FK_PROJECTINFO2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Projectinfo as(String alias) {
		return new Projectinfo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Projectinfo rename(String name) {
		return new Projectinfo(name, null);
	}
}
